# Applied Economics Software II — Week 2  
## Foundations of Scientific Computing with Python and NumPy
### Prepared by
**Eren Eskicioğlu**  
[GitHub](https://github.com/MrESKK)

##Basic Print Operations

In [ ]:
print(2+2)
print(2*2)
print(2-2*7) #order of the operations rule  we can use like this print(2-(2*7)) for not making mistake
print((2-2)*7)

4
4
-12
0


In [ ]:
2*2 # if we run the cod output of the cod will 4 but always we will see the last rows
2/2

1.0

In [ ]:
print("two times two =", 2*2) # "" means string or text also we can use a print as a calculater

two times two = 4


## Adding variable

In [ ]:
a = 2*2 # a is a variable

In [ ]:
print("Variable value is", a)

Variable value is 4


##Creating a vector (this is called as 'array')

In [ ]:
A_vector = [1,2,3,4]  # It can be number or string like A_vector = [1,2,3,4, "Eren"]


In [ ]:
#Chossing the part of the number in the vector
print(A_vector[2])   # print will be 3 because python is counting start the 0 when we count left to right

print(A_vector[-2])  # print will be 3 because python is start With negative indexing, the index starts from the end.
# not: if i write right to left index starts with -1


3
3


#Introduction to Numpy
NumPy (Numerical Python) is a fundamental library for numerical computing in Python.
It provides the powerful `ndarray` object, which enables efficient storage and manipulation of multi-dimensional data structures.

Unlike standard Python lists, NumPy arrays support:
- Vectorized operations (element-wise computation without explicit loops)
- High-performance numerical processing
- Broadcasting and advanced indexing
- Mathematical and statistical routines

In this section, we introduce basic array creation methods such as `np.array()`, `np.ones()`, `np.zeros()`, and `np.random.rand()`, which form the foundation for scientific computing, data analysis, and machine learning workflows.

For an [Official Beginner-Friendly Introduction to NumPy](https://numpy.org/doc/stable/user/absolute_beginners.html)


In [ ]:
# if we want to use package we have to call the package with import function
import numpy as np # as np means we use the munpy, you have to use like that np.array
#note: if you use a colab, you don't need to install the package but if you use local pc you have to install the package with this cod pip install numpy

In [ ]:
One_Vector = np.ones(4) # It creates vector with just all elements ara one, and inside of the parantheses means N element of vector
print(One_Vector)

Zero_Vector = np.zeros(4) # It creates vector with just all elements ara zero
print(Zero_Vector)

[1. 1. 1. 1.]
[0. 0. 0. 0.]


In [ ]:
Random_Vector = np.random.rand(4) # It creates vector with random elements
print(Random_Vector)

[0.18657956 0.53756193 0.05173932 0.03284952]


In [ ]:
One_Dimention_Vector = np.array([1,2,3,4]) #if we use [], we can create one dimention vector, only row

In [ ]:
One_Dimention_Vector[1]  # 1st index

np.int64(6)

In [ ]:
#square every elements of matrix
Sqrt_Matrix = One_Dimention_Vector**2
print(Sqrt_Matrix)

[ 1  4  9 16]


## NumPy Universal Functions (ufuncs) and Vectorized Mathematical Operations
We apply functions such as:

- square root (np.sqrt)
- absolute value (np.absolute)
- exponential (np.exp)
- minimum and maximum (np.min, np.max)
- sign detection (np.sign)
- logarithm (np.log)
- sinus (np.sin)
- Cosine (np.cos)

For additional mathematical operations, see the official [NumPy Mathematical Functions Documentation](https://numpy.org/doc/stable/reference/routines.math.html)

In [ ]:
ex_nump1 = np.array([-5,-4-3,-2,-1,0,1,2,3,4,5])
print(ex_nump1)

[-5 -7 -2 -1  0  1  2  3  4  5]


In [ ]:
print(np.sqrt(ex_nump1))  # Square route of each element

[       nan        nan        nan        nan 0.         1.
 1.41421356 1.73205081 2.         2.23606798]


/tmp/ipython-input-164/1233143274.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(ex_nump1))  # Square route of each element


In [ ]:
print(np.absolute(ex_nump1))  # Absolute value of each element

[5 7 2 1 0 1 2 3 4 5]


In [ ]:
print(np.exp(ex_nump1))  # Exponential of each element


[6.73794700e-03 9.11881966e-04 1.35335283e-01 3.67879441e-01
 1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02]


In [ ]:
print(np.min(ex_nump1))  # Minimum value
print(np.max(ex_nump1))  # Maximum value

-7
5


In [ ]:
print(np.sign(ex_nump1))  # Sign of each element (1 for positive, -1 for negative, 0 for zero)

[-1 -1 -1 -1  0  1  1  1  1  1]


In [ ]:
print(np.log(ex_nump1))  # Natural logarithm of each element


[       nan        nan        nan        nan       -inf 0.
 0.69314718 1.09861229 1.38629436 1.60943791]


/tmp/ipython-input-164/899933029.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(ex_nump1))  # Natural logarithm of each element
/tmp/ipython-input-164/899933029.py:1: RuntimeWarning: invalid value encountered in log
  print(np.log(ex_nump1))  # Natural logarithm of each element


In [ ]:
print(np.sin(ex_nump1))  # Sine of each element

[ 0.95892427 -0.6569866  -0.90929743 -0.84147098  0.          0.84147098
  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [ ]:
print(np.cos(ex_nump1))  # Cosine of each element

[ 0.28366219  0.75390225 -0.41614684  0.54030231  1.          0.54030231
 -0.41614684 -0.9899925  -0.65364362  0.28366219]


## Two Dimentions Functions

In [ ]:
Two_Dimention_Vector = np.array([[1,2,3,4],[5,6,7,8]]) # Creates a 2D NumPy array (a 2×4 matrix): 2 rows and 4 columns.
print(Two_Dimention_Vector)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
np.linspace(-10,10,21) # Generates 20 evenly spaced numbers between -10 and 10 (inclusive).
#for example: If you cannot remember the number of divisions, you can write this prompt to Gemini or GPT to get help.

#I want to generate evenly spaced integers between -10 and 10 using NumPy.
#When I use np.linspace(-10, 10, 20), I get float values.
#I want only integer values including both -10 and 10.
#What is the correct NumPy function to use, and why?

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

### Interactive 3D Surface Plot for a 2D NumPy Matrix
This section visualizes a two-dimensional NumPy matrix using an interactive 3D surface plot.

Each matrix element is represented as a height value (z-axis), while row and column indices define the x and y axes. This approach helps interpret matrix data in a spatial and intuitive way.

For a detailed explanation of [Plotly Surface Plots](https://www.youtube.com/watch?v=9GYmFXBitBw&list=PLBSCvBlTOLa8rf2kGkP_Bx5xXqT-er4Yq/)

In [ ]:
import numpy as np
import plotly.graph_objects as go   # Plotly for interactive visualization

# Create a 2D NumPy matrix
two_dimension_vector = np.array([[1, 2, 3, 4],
                                 [5, 6, 7, 8]])

# Create coordinate grids for X and Y axes
x = np.arange(two_dimension_vector.shape[1])  # Column indices
y = np.arange(two_dimension_vector.shape[0])  # Row indices
X, Y = np.meshgrid(x, y)  # Generate coordinate matrix

# Create interactive 3D surface plot
fig = go.Figure(data=[go.Surface(
    z=two_dimension_vector,  # Z values (matrix values)
    x=X,                     # X coordinates
    y=Y                      # Y coordinates
)])

# Update layout for better visualization
fig.update_layout(
    title="Interactive 3D Surface Plot of a 2D NumPy Matrix",
    scene=dict(
        xaxis_title="Columns",
        yaxis_title="Rows",
        zaxis_title="Matrix Values"
    )
)

# Display interactive plot
fig.show()

### Interactive Heatmap Visualization of a 2D NumPy Matrix
This section represents the same 2D NumPy matrix using an interactive heatmap.

Color intensity corresponds to numerical magnitude, making it easier to identify patterns, concentration, and relative differences within the matrix.

For a detailed explanation of [Plotly Heatmaps](https://www.youtube.com/watch?v=U4gjFYvQafo&t)

In [ ]:
import plotly.express as px

fig = px.imshow(two_dimension_vector,
                title="Interactive Heatmap of 2D NumPy Matrix",
                labels=dict(x="Columns", y="Rows", color="Value"))

fig.show()

## Applying a Quadratic Function on a NumPy Matrix and Finding the Maximum Value
### Loop-Based vs Vectorized Computation in NumPy (Quadratic Function Example)
In this section, we compare two approaches for applying a quadratic function

$$
f(x) = 5x^2 + 3
$$

to a NumPy matrix:

1. A loop-based implementation (explicit iteration).
2. A vectorized implementation (NumPy optimized computation).

The goal is to demonstrate the computational efficiency difference between pure Python loops and NumPy’s vectorized operations.

### Further Reading

For an intuitive explanation of replacing explicit loops with vectorized operations in Python:

[Ditch loops and Embrace vectorization (Medium)](https://medium.com/@vinodkumargr/ditch-loops-and-embrace-vectorization-25e578a5a4b7)

### 1) Loop-Based Approach (Explicit Iteration)
This implementation applies the function element-by-element using nested loops and manually tracks the maximum value.

In [ ]:
import numpy as np  # NumPy library is used for numerical operations and matrix handling

# Example matrix (2 rows, 3 columns)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])  # Creates a 2D NumPy array

# Function definition: y = 5x^2 + 3
def f(x):
    return 5*x**2 + 3  # Quadratic function

max_y = -np.inf  # Initialize maximum y as negative infinity (ensures first comparison works)
max_x = None     # Variable to store the x value that produces the maximum y

# Iterate through each row in the matrix
for row in matrix:
    # Iterate through each element in the current row
    for x in row:
        y = f(x)  # Apply the function to current element
        print(f"x = {x}, y = {y}")  # Print each calculation

        if y > max_y:  # Check if current y is greater than stored maximum
            max_y = y  # Update maximum y
            max_x = x  # Store corresponding x value

print("\nMaximum value:")
print("x =", max_x)  # x that gives the highest y
print("y =", max_y)  # Highest y value

x = 1, y = 8
x = 2, y = 23
x = 3, y = 48
x = 4, y = 83
x = 5, y = 128
x = 6, y = 183

Maximum value:
x = 6
y = 183


### 2) Vectorized Approach (NumPy Array Operations)
This implementation applies the function to the entire matrix at once using NumPy vectorized operations, then finds the maximum efficiently.

In [ ]:
import numpy as np

# Example matrix (2 rows, 3 columns)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Vectorized function application: f(x) = 5x^2 + 3 for all elements
y = 5 * matrix**2 + 3

print("y matrix (function values):\n", y)

# Maximum y value
max_y = np.max(y)

# Get 2D index of maximum
max_index = np.unravel_index(np.argmax(y), y.shape)    # np.unravel_index takes a flat index (from np.argmax) and returns its corresponding 2D position (row, column).

# Get corresponding x value
max_x = matrix[max_index]

print("\nMaximum value:")
print("x =", max_x)
print("y =", max_y)

y matrix (function values):
 [[  8  23  48]
 [ 83 128 183]]

Maximum value:
x = 6
y = 183


### 3) Benchmark: Loop vs Vectorized Performance
We compare execution time for the loop-based and vectorized approaches using a larger random matrix.

In [ ]:
import numpy as np
import time

# Create a large matrix for performance comparison
#matrix = np.array([[1, 2, 3],
#                   [4, 5, 6]])

matrix = np.random.rand(500, 500)
# ==================================================
# 1) Loop-Based Implementation
# ==================================================
start_time = time.time()

max_y_loop = -np.inf
max_x_loop = None

for row in matrix:
    for x in row:
        y_val = 5*x**2 + 3
        if y_val > max_y_loop:
            max_y_loop = y_val
            max_x_loop = x

loop_time = time.time() - start_time

# ==================================================
# 2) Vectorized Implementation
# ==================================================
start_time = time.time()

# Apply function to entire matrix at once
y_vec = 5 * matrix**2 + 3

# Maximum y value
max_y_vec = np.max(y_vec)

# Convert flat index (from argmax) into 2D index
max_index_vec = np.unravel_index(np.argmax(y_vec), y_vec.shape)

# Get corresponding x value
max_x_vec = matrix[max_index_vec]

vectorized_time = time.time() - start_time

# ==================================================
# Results
# ==================================================
print("Loop Version Time (seconds):", loop_time)
print("Vectorized Version Time (seconds):", vectorized_time)

print("\nLoop Max:")
print("x =", max_x_loop)
print("y =", max_y_loop)

print("\nVectorized Max:")
print("x =", max_x_vec)
print("y =", max_y_vec)

Loop Version Time (seconds): 0.11586928367614746
Vectorized Version Time (seconds): 0.0017495155334472656

Loop Max:
x = 0.9999982514369704
y = 7.999982514384992

Vectorized Max:
x = 0.9999982514369704
y = 7.999982514384992


## Solving a System of Linear Equations Using NumPy

Consider the following system of linear equations:

$$
x + 2y = 1
$$

$$
4x + 5y = 1
$$

This system can be written in matrix form as:

$$
A \cdot V = d
$$

Where:
$$
A =
\begin{bmatrix}
1 & 2 \\
4 & 5
\end{bmatrix}
$$

$$
V =
\begin{bmatrix}
x \\
y
\end{bmatrix}
$$

$$
d =
\begin{bmatrix}
1 \\
1
\end{bmatrix}
$$


---

### Why do we separate the system as A, V, and d?

- **A** is the coefficient matrix.  
  It contains the numerical coefficients of the variables.

- **V** is the variable (unknown) vector.  
  It represents the values we want to solve for (x and y).

- **d** is the constant vector.  
  It contains the values on the right-hand side of the equations.

This matrix representation allows us to solve the system using linear algebra methods instead of solving the equations manually.

---

### Mathematical Solution Concept

If matrix (A) is invertible, the solution can be written as:

$$
V = A^{-1} d
$$

However, instead of explicitly computing the inverse (which is computationally expensive and numerically unstable), NumPy provides:

$$
\texttt{np.linalg.solve(A, d)}
$$
or
$$
\texttt{np.dot(np.linalg.inv(A), d)}
$$

These functions directly computes the solution using efficient linear algebra algorithms ([LU decomposition](https://en.wikipedia.org/wiki/LU_decomposition)).

---
This approach scales efficiently to larger systems and is fundamental in scientific computing, econometrics, optimization, and machine learning.

In [ ]:
A = np.array([[1,2],[4,5]])
d = np.array([1,1])

#V = np.linalg.solve(A,d)    # Solves the linear system A @ V = d and returns the solution vector V.
V = np.linalg.inv(A) @ d     # If you want to use the inverse, the correct multiplication operator is @ or np.dot((np.linalg.inv(A),d)
V
#note: In Python, the @ operator performs matrix multiplication.




array([-1.,  1.])

In [ ]:
np.linalg.solve(A,d) # It takes matrix A and result vector d, and calculates the values of the variables automatically.

## Three-Dimensional Arrays: Structure, Shape, Indexing and Surface Plotting

In [ ]:
#Matrix inside a matrix
Three_Dimension_Vector = np.array([
    [[1, 2],
     [3, 4]],              # first 2x2 "layer"

    [[5, 6],               # second 2x2 "layer"
     [7, 8]],

    [[9, 7],               # third 2x2 "layer"
     [2, 4]]
])

In [ ]:
print(Three_Dimension_Vector)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[9 7]
  [2 4]]]


In [ ]:
print(Three_Dimension_Vector.shape)    # the output will be (3,2,2) means 3 matrix and 2x2

(3, 2, 2)


In [ ]:
Three_Dimension_Vector[1,1,0]  # Three_Dimension_Vector[layer, row, colum]

np.int64(7)

###NumPy Indexing and Slicing Examples
In a 2D NumPy matrix, indexing follows the structure:

$$
\texttt{array[row, column]}
$$

In a 3D NumPy matrix, indexing follows the structure:

$$
\texttt{array[layer, row, column]}
$$


In [ ]:
A = np.array([1,2,3,4,5,6])
A[2:-1]   # returns elements starting from index 2 up to (but not including) the last element.

array([3, 4, 5])

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a[0:,1:]   #selects all rows and columns starting from index 1 to the end.

array([[2, 3],
       [5, 6]])

### Combined 3D Surface Plot of All Layers in a 3D NumPy Array

In [ ]:
import numpy as np
import plotly.graph_objects as go

# Example 3D array (3 layers, each 2x2)
three_dimension_vector = np.array([
    [[1, 2],
     [3, 4]],

    [[12, -9],
     [-3, 1]],

    [[-2, 7],
     [9, -4]]
])

num_layers, rows, cols = three_dimension_vector.shape

# Coordinates for surfaces
x = np.arange(cols)
y = np.arange(rows)
X, Y = np.meshgrid(x, y)

fig = go.Figure()

# Add each layer as a separate surface with a vertical offset
z_offset = 10  # distance between layers (increase/decrease if needed)

for i in range(num_layers):
    Z = three_dimension_vector[i] + i * z_offset  # shift each layer upward

    fig.add_trace(
        go.Surface(
            z=Z,
            x=X,
            y=Y,
            name=f"Layer {i}",
            showscale=(i == 0)  # show colorbar only once (minimal look)
        )
    )

fig.update_layout(
    title="Combined 3D Surface Plot (All Layers in One Figure)",
    scene=dict(
        xaxis_title="Column Index",
        yaxis_title="Row Index",
        zaxis_title="Values (with layer offset)"
    )
)

fig.show()

#Writing a Definition
A function is a reusable block of code that performs a specific task.
It helps organize code, avoid repetition, and improve readability.

### Further Reading

For a complete reference of Python built-in functions, see the official documentation:

[Python Built-in Functions Documentation](https://docs.python.org/3/library/functions.html)

In [ ]:
def find_sqrt(x):
  return x**(1/2)   #The return statement outputs a value from a function so it can be used in other parts of the program.

In [ ]:
find_sqrt(4)

2.0

# References
The theoretical explanations and implementation techniques in this notebook are supported by the following official documentation and technical resources:

- NumPy Developers. *NumPy for Absolute Beginners*.  
  https://numpy.org/doc/stable/user/absolute_beginners.html

- NumPy Developers. *Mathematical Functions Reference*.  
  https://numpy.org/doc/stable/reference/routines.math.html

- Interactive 3D Surface Plot for a 2D NumPy Matrix. *Youtube*.                    
  https://www.youtube.com/watch?v=9GYmFXBitBw

- Interactive Heatmap Visualization of a 2D NumPy Matrix. *YouTube*.  
  https://www.youtube.com/watch?v=U4gjFYvQafo

- Kumar, V. *Ditch Loops and Embrace Vectorization*. Medium.  
  https://medium.com/@vinodkumargr/ditch-loops-and-embrace-vectorization-25e578a5a4b7

- LU Decomposition. *Wikipedia*.  
  https://en.wikipedia.org/wiki/LU_decomposition

- Python Software Foundation. *Built-in Functions*.  
  https://docs.python.org/3/library/functions.html